#!/usr/bin/env bash
#
# Build project.
# Source: https://setuptools.pypa.io/en/latest/build_meta.html

set -o errexit
set -o pipefail
set -o nounset

echo "Build project"

echo "Executing python3 -m build"
python3 -m build
